import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background-main": "#b2ccec",
        "surface-accent": "#f5c7c7",
        "surface-text-container": "#f2f2f2",
        "ink-primary": "#253558",
        "primary": "#47607c",
        "primary-container": "#b2ccec",
        "primary-fixed": "#d0e4ff",
        "primary-fixed-dim": "#afc9e9",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001d35",
        "on-primary-fixed-variant": "#2f4963",
        "on-primary-container": "#3d5772",
        "secondary": "#785556",
        "secondary-container": "#fdcfcf",
        "secondary-fixed": "#ffdad9",
        "secondary-fixed-dim": "#e9bcbc",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#795656",
        "on-secondary-fixed": "#2d1415",
        "on-secondary-fixed-variant": "#5e3e3f",
        "tertiary": "#4e5e83",
        "tertiary-container": "#b9c9f4",
        "tertiary-fixed": "#d9e2ff",
        "tertiary-fixed-dim": "#b6c6f1",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#081a3c",
        "on-tertiary-fixed-variant": "#36466a",
        "on-tertiary-container": "#445479",
        "surface": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e2e2e2",
        "surface-tint": "#47607c",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#43474d",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",
        "outline": "#73777e",
        "outline-variant": "#c3c6ce",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#afc9e9",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "gutter": "1rem",
        "stack-sm": "0.5rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        soft: "0 4px 24px rgba(37, 53, 88, 0.08)",
        card: "0 2px 12px rgba(37, 53, 88, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
